### ISSUE TITLE
How to configure group id on message driven channel adapter

### ISSUE THREAD

**Issue by lucas-cegatti** [spring-projects/spring-integration-kafka#102]
Hi, I'm trying to migrate to message driven channel adapter, currently I'm using consumer context and inbound channel adapter. But I can't get it working the same way it is now. I need listeners (on different machines) to use the same group id, so kafka can distribute accordingly the messages between these listeners, our producer send messages with message key on the header.

What I'm getting with message driven channel adapter is all listeners receving all the messages. Is there a way to configure the same behavior when using consumer context and inbound channel adapter?

Versions:

			<dependency>
				<groupId>org.springframework.integration</groupId>
				<artifactId>spring-integration-kafka</artifactId>
				<version>1.3.0.RELEASE</version>
			</dependency>
			<dependency>
				<groupId>org.springframework.integration</groupId>
				<artifactId>spring-integration-core</artifactId>
				<version>4.1.2.RELEASE</version>
			</dependency>

**Comment by garyrussell** [comment]
Unlike the polled adapter, the message-driven adapter uses the simple consumer (not the high-level consumer, which supports consumer groups).

Instead of having group members compete for messages, the model is to use partitions to distribute work to consumers.

**Comment by lucas-cegatti** [comment]
Understood, thanks!

**Comment by lucas-cegatti** [comment]
Both consumer context and inbound channel adapter are deprecated, does it means that anytime soon the lib will not support high-level consumer? What is the recomendation? Migrate to the simple consumer?

**Comment by mbogoevici** [comment]
Hi Lucas,

We intend to move forward by migrating Spring Integration Kafka to Kafka 0.9, but that will happen in Spring Integration Kafka 2.0. The general intent here is to support all the new client features, including consumer group support, for the message driven channel adapter. We will most likely introduce a polled channel adapter as well.

The reason why we moved away from the high level consumer is highlighted in the link the Gary previously posted. It has too many issues and has limited functionality foo (e.g. listening to specific partitions and offsets is not possible), so we decided to go with the simple consumer approach instead. 

For now, if it is possible for you to configure the different clients to listen to different partitions of a topic, you can switch to the simple consumer-based message-driven channel adapter. (In practice, this is what the high level consumer and the new consumer do as well, internally - they distribute partitions between the different clients that belong to a consumer group. The advantage of doing it manually is that it is a deterministic process, and avoids shuffling listened partitions around when clients die/come back). 

If not, you can keep using the existing high-level-consumer-based client with the caveat that we will eventually consolidate all behaviour in the message driven channel adapter (based on the new client, as described above), which is the intent behind the deprecation.

Hope this helps,
Marius

**Comment by lucas-cegatti** [comment]
Marius, that's excellent news, looking forward the consumer group support on the message driven channel.

In the meantime I'll try to develop a solution assigning partitions.

Thanks & Regards.

**Comment by garyrussell** [comment]
Please note that the first milestone of Spring Integration Kafka 2.0 (based on the 0.9.0.x client is now available: https://spring.io/blog/2016/04/11/spring-integration-kafka-support-2-0-0-m1-is-now-available

This is based on the new [spring-kafka](https://spring.io/blog/2016/04/11/spring-for-apache-kafka-1-0-milestone-2-available) project.

**Comment by artembilan** [comment]
See here: https://spring.io/blog/2016/07/04/spring-for-apache-kafka-1-0-and-spring-integration-kafka-2-0-go-ga.

The `gpoupId` right now must as regular part of `Consumer` configs:
```

Map<String, Object> props = new HashMap<>();
...
props.put(ConsumerConfig.GROUP_ID_CONFIG, group);
...
DefaultKafkaConsumerFactory<Integer, String> cf = new DefaultKafkaConsumerFactory<Integer, String>(props);
ContainerProperties containerProps = new ContainerProperties(topic1);
...
KafkaMessageListenerContainer<Integer, String> container =
				new KafkaMessageListenerContainer<>(cf, containerProps);
KafkaMessageDrivenChannelAdapter<Integer, String> adapter = new KafkaMessageDrivenChannelAdapter<>(container);
```
Also see the sample on the matter: https://github.com/spring-projects/spring-integration-samples/tree/master/basic/kafka
