### ISSUE TITLE
rawHeaders are unusued in KafkaMessageDrivenChannelAdapter.toMessage()

### ISSUE THREAD

**Issue by eljuegodeender** [spring-projects/spring-integration-kafka#103]
I mean that this code snippet in line 197 is dead.
```java
Map<String, Object> rawHeaders = kafkaMessageHeaders.getRawHeaders();
rawHeaders.put(KafkaHeaders.MESSAGE_KEY, key);
rawHeaders.put(KafkaHeaders.TOPIC, metadata.getPartition().getTopic());
rawHeaders.put(KafkaHeaders.PARTITION_ID, metadata.getPartition().getId());
rawHeaders.put(KafkaHeaders.OFFSET, metadata.getOffset());
rawHeaders.put(KafkaHeaders.NEXT_OFFSET, metadata.getNextOffset());

if (!this.autoCommitOffset) {
	rawHeaders.put(KafkaHeaders.ACKNOWLEDGMENT, acknowledgment);
}
 ```

**Comment by mbogoevici** [comment]
I don't understand what you mean. This is shortcut for `kafkaMessageHeaders.getRawHeaders()`, which is used to set the headers of the sent message. 

If you wish to understand how this works, I will suggest running one of the tests that exercise header propagation, such as `org.springframework.integration.kafka.config.xml.KafkaMessageDrivenChannelAdapterParserTests`.

If you have an actual case where this doesn't work, than feel free to open a new one with a more detailed description.

**Comment by eljuegodeender** [comment]
Hi, sorry if I'm missing something but the point is that "rawHeaders" are not used during Message creation, only kafkaMessageHeaders are used.

```java
if (this.useMessageBuilderFactory) {
			return getMessageBuilderFactory()
					.withPayload(payload)
					.copyHeaders(kafkaMessageHeaders)
					.build();
		}
		else {
			return MessageBuilder.createMessage(payload, kafkaMessageHeaders);
		}
```
You're right tests are working as expected.

**Comment by artembilan** [comment]
1. Even if it (`rawHeaders`) is local variable it is a reference to the real object. That is how Java works.
2. See the `KafkaMessageHeaders` source code. it is a `Map` anyway. and it is an *immutable* wrapper around `rawHeaders` `Map`.
3. You might be correct that we will have the same result even with the `rawHeaders` here, but it is fully minor and I don't see reason to rework.
