### ISSUE TITLE
Reinstate the ability to send messages synchronously

### ISSUE THREAD

**Issue by mbogoevici** [spring-projects/spring-integration-kafka#125]
In the 1.3 version we used to have a setting for the `KafkaProducingMessasgeHandler` that allowed opting between asynchronous (default) and synchronous sending of messages (via the old `ProducerConfiguration`). 

While asynchronous sending is preferred for performance reasons, synchronous sending allows the sender to block until a message is received and to ensure that any sending exception is thrown in the caller's thread

With the migration to the `KafkaTemplate`, the ability of sending messages synchronously seems to have been lost.

**Comment by artembilan** [comment]
From big height I don't mind for such a feature.

Only concern is that I'd like to move this project into Spring Integraiton 5.0. 
Therefore I don't want to have any changes here until that time.

If that is only IMO and we can still live with this project in the separate repo, let's consider to fix it as it is proposed. 

But bear in mind that we can't expose XML `sync` attribute until `2.1` version.

Any other thoughts are welcome!

CC @sobychacko

**Comment by mbogoevici** [comment]
Yeah, it's blocking a pretty important feature in the 1.1 Kafka binder, unfortunately.
