### ISSUE TITLE
The spring-integration-kafka 2.0 jar can't support earlier than 4.0 version Spring.

### ISSUE THREAD

**Issue by abc112358** [spring-projects/spring-integration-kafka#128]
I use the spring-integration-kafka 2.0 jar , spring-kafka 1.0.2 jar and version 3.2.13 Spring ,but the error "ClassNoFound" occur,that's because some classes which are referred in spring kafka 1.0.2 in the 4.0 or later Spring, 
not in the earlier than 4.0 Spring.but the document is shown that "Tested with Spring Framework version dependency is 4.2.5 but it is expected that the framework will work with earlier versions of Spring.".
so I am confused.
thank u.

**Comment by artembilan** [comment]
Well, we didn't test the project against Spring 3.2.13, indeed, and, eh, there is really no plans to do that.
You really should consider to upgrade to Spring 4.x. Would be much better to the latest one.
With that old version you even can't use Spring Boot.
More over: Spring Integration Kafka 2.0 is based on the Spring Integration 4.2, which isn't compatible with Spring 3.2 for a long time already as well.
So, you have very big issue if you would like to use Spring Integration Kafka and don't want to upgrade the foundation like Spring Framework.

That phrase means "all 4.x" line ony, sorry.

Closed with no workarounds.
All the more so you are talking about Spring Kafka, not Spring Integration Kafka 2.0: http://docs.spring.io/spring-kafka/reference/html/_introduction.html#compatibility

**Comment by abc112358** [comment]
Thank you so much about your reply,and I have another uncertainty ,that is the relation between the Spring Kafka and Spring Integration Kafka 2.0.
And I think the all related codes is in the Spring Integration Kafka 1.3.x project,but it's divided to two project when 2.0 ,one which contained the client code  is Spring Integration Kafka 2.0 and the other one which contained the code expect the client code is the Spring Kafka 1.0.x.
and I don't known whether my understanding is correct, and if correct , but why divided to such two project.
I expect your reply,thank you very mush.

**Comment by garyrussell** [comment]
Spring Integration Kafka 1.x used the kafka 0.8.x.x client directly; there was no spring-kafka project at that time.

For the 0.9.x.x client (and above) we decided to create a generic spring-kafka project to provide a general Spring abstraction ([web site here](http://projects.spring.io/spring-kafka/)) for any Spring users who might not want to use Spring Integration but like spring abstractions such as the `KafkaTemplate` and `@KafkaListener` annotation.

spring-integration-kafka Version 2.0 is built on top of the new spring-kafka project and does not use the kafka client directly. It is a completely new project.

I hope that explains the evolution of these projects.

**Comment by abc112358** [comment]
I understand the evolution of these projects now ,thank you so mush.
