### ISSUE TITLE
BlockingQueue storage object  memory out of range 

### ISSUE THREAD

**Issue by dingzai** [spring-projects/spring-integration-kafka#132]
Hi,everyBody!
   i use spring-integration-kafka encountered a problem,the time spent more consumption message,but the spring-integration PollableChannel object always receive message put in BlockingQueue list, so the list more and more big, end up memory out of range.  
  example:

``` java
public void run() {
        log.debug("【0.完成接收】");
        while (true) {
            Message<?> received = pollableChannel.receive(1000);
            if (received == null) {
                try {
                    Thread.sleep(1000L);
                } catch (InterruptedException e) {
                    e.printStackTrace();
                }
                continue;
            }
            try {
                targetService.writeDatas((List<RTDataSet>) received.getPayload());
            } catch (SyncException e) {
                e.printStackTrace();
            }
            log.debug("【1.完成写入】");
        }
    }
```

targetService.writeDatas method run slow, The  QueueChannel class ----> doReceive method ,Take a data, and then delete the consumption data from the BlockingQueue array,doSend method responsible for repeated to add consumption data in an array, the array more and more big,i don't know i user the method wrong?  anybody can hlep me?
my config:

``` java
@Bean
    public KafkaMessageListenerContainer<String, String> receiverContainer() {
        return new KafkaMessageListenerContainer<>(receiverConsumerFactory(),
                new ContainerProperties(new TopicPartitionInitialOffset(this.topic, 0)));
    }

    @Bean
    public ConsumerFactory<String, String> receiverConsumerFactory() {
        Map<String, Object> props = new HashMap<>();
        props.put(ConsumerConfig.BOOTSTRAP_SERVERS_CONFIG, this.brokerAddress);
        props.put(ConsumerConfig.GROUP_ID_CONFIG, "siTestGroup");
        props.put(ConsumerConfig.ENABLE_AUTO_COMMIT_CONFIG, false);
        props.put(ConsumerConfig.AUTO_COMMIT_INTERVAL_MS_CONFIG, 100);
        // props.put(ConsumerConfig.SESSION_TIMEOUT_MS_CONFIG, 15000);
        props.put(ConsumerConfig.KEY_DESERIALIZER_CLASS_CONFIG, StringDeserializer.class);
        props.put(ConsumerConfig.VALUE_DESERIALIZER_CLASS_CONFIG, SyncMqDeserializer.class);
        return new DefaultKafkaConsumerFactory<>(props);
    }

    @Bean
    public KafkaMessageDrivenChannelAdapter<String, String> receiverAdapter() {
        KafkaMessageDrivenChannelAdapter<String, String> kafkaMessageDrivenChannelAdapter = new KafkaMessageDrivenChannelAdapter<>(
                receiverContainer());
        kafkaMessageDrivenChannelAdapter.setOutputChannel(receivedServiceKafka());
        return kafkaMessageDrivenChannelAdapter;
    }

    @Bean
    public PollableChannel receivedServiceKafka() {
        return new QueueChannel();
    }
```

**Comment by garyrussell** [comment]
Use a `DirectChannel` instead of a `QueueChannel`; that way, your flow will run on the container thread and the container will pause the consumer if your flow can't keep up. The consumer will be resumed automatically when the listener catches up.

**Comment by garyrussell** [comment]
Oh; I see you are using the sample app as a guide.

To switch to a subscribable channel:

```java
	public static void main(String[] args) throws Exception {
		ConfigurableApplicationContext context
				= new SpringApplicationBuilder(Application.class)
				.web(false)
				.run(args);
		SubscribableChannel fromKafka = context.getBean("received", SubscribableChannel.class);
		fromKafka.subscribe(new MessageHandler() {

			@Override
			public void handleMessage(Message<?> message) throws MessagingException {
				System.out.println(message);
			}
		});
		MessageChannel toKafka = context.getBean("toKafka", MessageChannel.class);
		for (int i = 0; i < 10; i++) {
			toKafka.send(new GenericMessage<>("foo" + i));
		}
	}
   ...
	@Bean
	public SubscribableChannel received() {
		return new DirectChannel();
	}
```

But it would actually be better to use other Spring Integration components - use a service activator to invoke your code.

**Comment by dingzai** [comment]
thanks for garyrussell, use SubscribableChannel can get messageChannel publish data,but the one can't get kafka historyData,i'm make sure data don't lost..  can you give me some advice?thanks again 

` public static void main(String[] args) throws Exception {
        ConfigurableApplicationContext context
                = new SpringApplicationBuilder(Application.class)
                .web(false)
                .run(args);

        MessageChannel toKafka = context.getBean("toKafka", MessageChannel.class);
        for (int i = 0; i < 10; i++) {
            toKafka.send(new GenericMessage<>("foo" + i));
        }

        SubscribableChannel fromKafka = context.getBean("received", SubscribableChannel.class);
        fromKafka.subscribe(new MessageHandler() {

            @Override
            public void handleMessage(Message<?> message) throws MessagingException {
                System.out.println(message);
            }
        });
    }
`

can not get historyData..

**Comment by dingzai** [comment]
@garyrussell   

thanks for garyrussell, use SubscribableChannel can get messageChannel publish data,but the one can't get kafka historyData,i'm make sure data don't lost.. can you give me some advice?thanks again

` public static void main(String[] args) throws Exception {
ConfigurableApplicationContext context
= new SpringApplicationBuilder(Application.class)
.web(false)
.run(args);

    MessageChannel toKafka = context.getBean("toKafka", MessageChannel.class);
    for (int i = 0; i < 10; i++) {
        toKafka.send(new GenericMessage<>("foo" + i));
    }

    SubscribableChannel fromKafka = context.getBean("received", SubscribableChannel.class);
    fromKafka.subscribe(new MessageHandler() {

        @Override
        public void handleMessage(Message<?> message) throws MessagingException {
            System.out.println(message);
        }
    });
}
`

can not get historyData..

**Comment by garyrussell** [comment]
You have to subscribe before you send any data - see my example above.

If I get time today, I'll rewrite the sample to use more usual Spring Integration concepts.

Also, please see how I edited your question to format properly; you can't use a single back-tick to scope a code block.

**Comment by artembilan** [comment]
Closed with the fix provided above, plus as out-dated.
