### ISSUE TITLE
Conflicting zk dependency

### ISSUE THREAD

**Issue by fizwhiz** [spring-projects/spring-integration-kafka#133]
On adding the spring-integration-kafka dependency, I notice it bundles conflicting zookeeper dependencies with versions `3.3.1` and `3.4.6` (exposed via the dependency-convergence plugin goal in my maven lifecycle):

```
[INFO] --- maven-enforcer-plugin:1.3.1:enforce (conflicting-jar-version-enforce) @ myAppDaemon ---
[WARNING] Rule 0: org.apache.maven.plugins.enforcer.DependencyConvergence failed with message:
Failed while enforcing releasability the error(s) are [
Dependency convergence error for org.apache.zookeeper:zookeeper:3.4.6 paths to dependency are:
+-com.paypal.user.shadow:usershadowreplaydDaemon:0.0.1-SNAPSHOT
  +-org.springframework.integration:spring-integration-kafka:1.3.0.RELEASE
    +-org.apache.kafka:kafka_2.10:0.8.2.2
      +-org.apache.zookeeper:zookeeper:3.4.6
and
+-com.paypal.user.shadow:usershadowreplaydDaemon:0.0.1-SNAPSHOT
  +-org.springframework.integration:spring-integration-kafka:1.3.0.RELEASE
    +-org.apache.kafka:kafka_2.10:0.8.2.2
      +-com.101tec:zkclient:0.3
        +-org.apache.zookeeper:zookeeper:3.3.1
```

I'd like to know what the guidance is in resolving this conflicting version. For now, I'm "managing" the dependency by forcing version `3.3.1` but making assumptions in the process. Can someone verify whether this version is appropriate, and whether there's a desire to fix this conflicting dependency?

**Comment by artembilan** [comment]
Let's look to that report one more time!
```
 +-org.apache.kafka:kafka_2.10:0.8.2.2
      +-org.apache.zookeeper:zookeeper:3.4.6
```
and
```
 +-org.apache.kafka:kafka_2.10:0.8.2.2
      +-com.101tec:zkclient:0.3
        +-org.apache.zookeeper:zookeeper:3.3.1
```
so, both are exactly transitive dependencies from Kafka.
Spring Integration doesn't provide any ZK dependency and just relies on that one from Kafka.

Not sure what you would like to see as a fix from our side, but that fully looks like a problem in Apache Kafka. Therefore the report must be moved to their bug tracker.

WDYT?

**Comment by fizwhiz** [comment]
@artembilan you're absolutely right, i missed that they were coming from apache kafka directly. I'll report an issue on their github. Cheers!
