### ISSUE TITLE
topic-expression parse error

### ISSUE THREAD

**Issue by rchzzjcn** [spring-projects/spring-integration-kafka#136]
I tried with the following XML configuration:
```xml
    <int-kafka:outbound-channel-adapter id="kafkaOutboundChannelAdapter"
                                        kafka-template="testKafkaTemplate"
                                        auto-startup="true"
                                        channel="testInputToKafkaChannel"
                                        topic-expression="headers.kafka_topic == null ? 'test.topic' : headers.kafka_topic"
                                        >
    </int-kafka:outbound-channel-adapter>
```
And I send a message without explicitly set the "kafka_topic" header:
```
  Message<?> message = MessageBuilder.withPayload( "foo" + i)
                         // .setHeader(KafkaHeaders.TOPIC, "test.topic")
                         .build();
  messageChannel.send(message);
```

But it throws the following error:
```
Caused by: org.springframework.expression.spel.SpelEvaluationException: EL1008E:(pos 8): Property or field 'kafka_topic' cannot be found on object of type 'org.springframework.messaging.MessageHeaders' - maybe not public?
...

	at org.springframework.integration.kafka.outbound.KafkaProducerMessageHandler.handleMessageInternal(KafkaProducerMessageHandler.java:116)
	at org.springframework.integration.handler.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:127)
```

**Comment by rchzzjcn** [comment]
One solution is using the following:
```
    <int-kafka:outbound-channel-adapter id="kafkaOutboundChannelAdapter"
                                        kafka-template="testKafkaTemplate"
                                        auto-startup="true"
                                        channel="testInputToKafkaChannel"
                                        topic-expression="headers['kafka_topic'] == null ? 'test.topic' : headers['kafka_topic']"
                                        >
    </int-kafka:outbound-channel-adapter>
```

**Comment by rchzzjcn** [comment]
BTW, the spring-kafka reference(1.0.3)  document mentioned the following:
```
topic-expression="headers.topic != null ? headers.topic : 'myTopic'".
```

It seems need to be corrected.

**Comment by garyrussell** [comment]
Yes, this is correct. I generally prefer to use the map accessor syntax `headers['foo']` rather than the property accessor syntax `headers.foo` - because the property accessor doesn't work with dotted properties `foo.bar` and the map accessor is null-safe.

We will fix the reference document.

**Comment by rchzzjcn** [comment]
@garyrussell , I checked your fix, but it still has other problems.
According to the source code (KafkaHeaders.java)
```
public static final String MESSAGE_KEY = PREFIX + "messageKey";
```
which means that the MESSAGE_KEY is now "kafka_messageKey" instead of "messageKey", so it seems we need to use the following:
```
headers['kafka_messageKey']"
```
instead of 
```
headers['messageKey']"
```

The same with "partitionId".

**Comment by artembilan** [comment]
@rchzzjcn, I'm not sure in your question.

The `headers['kafka_messageKey']` and `headers['messageKey']` are both custom expressions for custom headers. That is just coincidental that `kafka_messageKey` is fully equal to `MESSAGE_KEY` constant.

Please, be more specific.
Where do you see problem?

**Comment by garyrussell** [comment]
> which means that the MESSAGE_KEY is now "kafka_messageKey" instead of "messageKey"

That is explained in the **IMPORTANT** note in the [README](https://github.com/spring-projects/spring-integration-kafka#outbound-channel-adapter).
