### ISSUE TITLE
Add "send-timeout" to the <int-kafka:outbound-channel-adapter> 

### ISSUE THREAD

**Issue by artembilan** [spring-projects/spring-integration-kafka#145]
See setter on the `KafkaProducerMessageHandler`:
````java
/**
 * Specify a timeout in milliseconds how long {@link KafkaProducerMessageHandler}
 * should wait wait for send operation results. Defaults to 10 seconds.
 * @param sendTimeout the timeout to wait for result fo send operation.
 */
public void setSendTimeout(long sendTimeout) {
	this.sendTimeout = sendTimeout;
}
````

**Comment by artembilan** [comment]
Since we have relaxed XSD changes rules for the additions, I find this issue as valuable to be fixed in the current `2.1.1` version.
Also I'm going to consider `sendTimeoutExpression` since there might be some cases when we should wait for the completion with different values from message to message.

**Comment by garyrussell** [comment]
👍

**Comment by garyrussell** [comment]
The javadoc for the setter should say `Only applies when sync is set to true.`.
