### ISSUE TITLE
Consumer stops getting messages when partition leader dies

### ISSUE THREAD

**Issue by bonii-xx** [spring-projects/spring-integration-kafka#152]
I have a setup consisting of 2 Kafka broker (0 and 1) using a zookeeper, a spring boot application with producers and a spring boot application with consumers.

The topic has 5 partitions and a replication factor of 2, both brokers are in sync, partitions have alternating leader (although it doesn't matter).

The spring boot kafka configuration is setup as follows:

    kafka.address: localhost:9092,localhost:9093
    kafka.numberOfConsumers: 20

Where Broker 0 uses port 9092 and Broker 1 uses port 9093.

---

When sending events they are consumed just fine. When Broker 0 is killed all topics get Broker 1 as their leader, however the consumers stop consuming events until Broker 0 is back. This happens nearly every time, but usually it takes at most 3 attempts of alternatively killing the leading broker to create the error state.

The console log is getting spammed by the coordinators, it looks like the coordinator representing broker 0 is marked as dead, but instantly rediscovered and used again many many times, and only at the end the other broker is discovered. When the switch works the log is only minimally spammed and the other broker is discovered very quickly.

[This gist](https://gist.github.com/bonii-xx/2f1c122f643019a1525fbe120e9162d8) contains the log of the application when the problem occurs. The first line is a log of ours indicating a successfully consumed message. After that the Broker 0 (localhost:9092) is killed - you can see the log spam I was talking about. At the end localhost:9093 is discovered, however no further messages are consumed. After that I killed the application.

---

I also discovered [this](https://stackoverflow.com/questions/39650993/kafka-consumer-abstractcoordinator-discovered-coordinator-java-client) unresolved stackoverflow question, which seems to be the same problem.

**Comment by artembilan** [comment]
Do you have similar question on Apache Kafka forums directly? Looks like there is nothing what we can do from Spring perspective. We only create `Consumer` and it all the properties, including `bootstrap.servers`. Spring Kafka doesn't have any impact for mentioned Coordinator.

**Comment by bonii-xx** [comment]
I have not, perhaps you could direct me there? Looks like their issue tracker is read only.

**Comment by artembilan** [comment]
I think you should just follow with Apache Kafka recommendations: https://kafka.apache.org/contact.

**Comment by bonii-xx** [comment]
I've put up an issue in their jira.

**Comment by artembilan** [comment]
@bonii-xx , would you mind sharing that JIRA ticket here for the whole picture?
Thanks

**Comment by bonii-xx** [comment]
Sure: https://issues.apache.org/jira/browse/KAFKA-4460

**Comment by bonii-xx** [comment]
Indeed, I did not see that. Thanks for pointing it out.
