### ISSUE TITLE
Acknowledgment AckMode.BATCH

### ISSUE THREAD

**Issue by boban74** [spring-projects/spring-integration-kafka#154]
Hi,

for consuming a kafka topic I'm using  PollingConsumer and KafkaMessageListenerContainer . I would like to use AckMode.BATCH and commit offset after all polled messages are processed. Spring Kafka documentation AckMode.BATCH - commit the offset when all the records returned by the poll() have been processed. What does it mean [have been processed] in the documentation, when is a message considered processed? Can I set the processed status of a message manually?

Regards Boban

**Comment by garyrussell** [comment]
The container polls the consumer, gets N messages; the container then invokes the listener for each individual message; when the listener returns after handling the __last__ message from the poll, the offset is committed.

So "processed" in this case simply means that the listener method returns.

**Comment by boban74** [comment]
Hi Gary,

thank you for your fast reply ... hm, i have no idea how to use spring integration kafka without loosing messages if my spring integration kafka application crashes. Currently I'm using a QueueChannel and a periodic trigger. In the queue channel are always buffered consumed messages but not processed by my application. The offset is then commited on last consumed message + 1 position. If then my application crashes all messages in the queue channel will be lost. No matter if I'm using manual or auto commit. There could be consumed messages int the queue but not processed by my application. What policy can i use here to not loose messages?

Thank you,
Regards boban

**Comment by garyrussell** [comment]
>Currently I'm using a QueueChannel and a periodic trigger.

__You should not use a `QueueChannel`__ - the offsets will be committed as soon as the messages are written to the queue.

Use a `DirectChannel` and your code will be executed on the container thread and won't be committed until your code completes its work.
