### ISSUE TITLE
Event when a topic is completely consumed

### ISSUE THREAD

**Issue by boban74** [spring-projects/spring-integration-kafka#156]
For consuming a topic I'm using KafkaMessageDrivenChannelAdapter and KafkaMessageListenerContainer ... is there any event when topic has no more messages, is completely consumed? How can i check this?

Regards Boban

**Comment by garyrussell** [comment]
Please read the documentation [Detecting Idle Asynchronous Consumers](http://docs.spring.io/spring-kafka/docs/1.1.2.RELEASE/reference/html/_reference.html#idle-containers).
