### ISSUE TITLE
How can I set consumer property "security.protocol" in application.yml?

### ISSUE THREAD

**Issue by otakun** [spring-projects/spring-integration-kafka#157]
Hi,

Maybe this is a stupid question, but I can't find a way to set the consumer property `security.protocol` in `application.yml` file.
I got it working using a bean for `ConsumerFactory`, but isn't there an easy way to do it directly in yml file?

Thanks for the help

Here the code snippet I currently use:
````java
    @Bean
    public ConsumerFactory<?, ?> kafkaConsumerFactory(KafkaProperties properties) {
        Map<String, Object> consumerProperties = properties.buildConsumerProperties();
        consumerProperties.put("security.protocol", "SSL");
        return new DefaultKafkaConsumerFactory<>(consumerProperties);
    }
`````

**Comment by artembilan** [comment]
You can configure SSL via these properties:
```
spring.kafka.consumer.ssl.key-password= # Password of the private key in the key store file.
spring.kafka.consumer.ssl.keystore-location= # Location of the key store file.
spring.kafka.consumer.ssl.keystore-password= # Store password for the key store file.
spring.kafka.consumer.ssl.truststore-location= # Location of the trust store file.
spring.kafka.consumer.ssl.truststore-password= # Store password for the trust store file.
```
See Spring Boot Manual: http://docs.spring.io/spring-boot/docs/1.5.0.RC1/reference/htmlsingle/#common-application-properties

Or do you mean that with all those SSL option we have just missed a general one `security.protocol`?

You can workaround it via general `properties` option:
```
spring.kafka.properties.security.protocol=SSL
```
http://docs.spring.io/spring-boot/docs/1.5.0.RC1/reference/htmlsingle/#boot-features-kafka-extra-props

**Comment by luchob** [comment]
Maybe he meant the second one and you really missed it. I also struggled with the same problem when I came to your post. The workaround:

```
spring:
  kafka:
    properties:
      security.protocol: "SSL"
```

...seem to work.

**Comment by artembilan** [comment]
Thank you, @luchob , for confirmation!

I'm closing this issue since there is nothing to do from the Spring Integration Kafka perspective and everything we are talking about is in the Spring Boot.

That's also good that we have a workaround.

If you all still strongly feel we need that property, please, raise an issue in the Spring Boot.

**Comment by Woodz** [comment]
> Thank you, @luchob , for confirmation!
> 
> I'm closing this issue since there is nothing to do from the Spring Integration Kafka perspective and everything we are talking about is in the Spring Boot.
> 
> That's also good that we have a workaround.
> 
> If you all still strongly feel we need that property, please, raise an issue in the Spring Boot.

Raised https://github.com/spring-projects/spring-boot/issues/19220 to add to SpringBoot
