### ISSUE TITLE
Timeout Exception while Sending Message

### ISSUE THREAD

**Issue by dgurav** [spring-projects/spring-integration-kafka#169]
org.springframework.kafka.core.KafkaProducerException: Failed to send; nested exception is org.apache.kafka.common.errors.TimeoutException: Failed to update metadata after 60000 ms. at org.springframework.kafka.core.KafkaTemplate$1.onCompletion(KafkaTemplate.java:255) at org.apache.kafka.clients.producer.KafkaProducer.doSend(KafkaProducer.java:490) at org.apache.kafka.clients.producer.KafkaProducer.send(KafkaProducer.java:440) at org.springframework.kafka.core.DefaultKafkaProducerFactory$CloseSafeProducer.send(DefaultKafkaProducerFactory.java:156) at org.springframework.kafka.core.KafkaTemplate.doSend(KafkaTemplate.java:241) at org.springframework.kafka.core.KafkaTemplate.send(KafkaTemplate.java:157) at org.tiaa.atom.core.support.kafka.DefaultKafkaESBSupport.convertAndSend(DefaultKafkaESBSupport.java:282) at org.tiaa.atom.core.support.kafka.DefaultKafkaESBSupport.send(DefaultKafkaESBSupport.java:114) at org.tiaa.usersecuritydata.repository.KafkaRepository.invokeThread(KafkaRepository.java:39) at org.tiaa.usersecuritydata.work.UserSecurityRSWorkImpl.run(UserSecurityRSWorkImpl.java:45) at org.tiaa.atom.core.concurrent.DelegatingContextWork.run(DelegatingContextWork.java:52) at weblogic.work.j2ee.J2EEWorkManager$WorkWithListener.run(J2EEWorkManager.java:184) at weblogic.work.ExecuteThread.execute(ExecuteThread.java:311) at weblogic.work.ExecuteThread.run(ExecuteThread.java:263) Caused by: org.apache.kafka.common.errors.TimeoutException: Failed to update metadata after 60000 ms.

**Comment by artembilan** [comment]
You know, we don't use GH for questions.
There is plenty of community forums with an appropriate help.

More over your questions isn't readable and, to be honest, there is even no a question.

Please, rephrase your post if you seek some help.

**Comment by artembilan** [comment]
Closed as non-relevant and badly formatted.
