### ISSUE TITLE
Missing spring-integration-kafka.xsd?

### ISSUE THREAD

**Issue by nobusue** [spring-projects/spring-integration-kafka#18]
I've got 404(Not Found) for XSD file:
http://www.springframework.org/schema/integration/kafka/spring-integration-kafka.xsd

Where is right location?

**Comment by artembilan** [comment]
@nobusue , thank you for the feedback!

It is located in the `spring-integration-kafka-1.0.0.RELEASE.jar`.
The modern IDE (IDEA, STS) can resolve those XSDs from classpath: 

We'll take a look to that `http://www.springframework.org/schema/integration/` resource and see what we can do, but anyway would be better to use any XSD from the jars which are dependency for your project.

Cheers

**Comment by garyrussell** [comment]
@artembilan is correct; Spring (and spring-aware IDEs) resolves the schema from the classpath; however, I have now added the schema online.
