### ISSUE TITLE
Add .headerMapper() to outbound channel adapter spec

### ISSUE THREAD

**Issue by garyrussell** [spring-projects/spring-integration-kafka#180]
Subject says it all - allow configuration of a header mapper.

**Comment by garyrussell** [comment]
No squash?

**Comment by artembilan** [comment]
> No squash?

Yeah... My fault.

Was so simple PR that I forgot to select `Squash & Merge` option here on GH. And just pressed `Rebase & Merge`.

But I guess it's not so critical - the history is still linear and that doesn't worth to re-write it for this squashing reason.

**Comment by garyrussell** [comment]
Agreed - just wondered what happened 😄
