### ISSUE TITLE
Incorrect catchExecutor for java.util.Date(Long) constructor.

### ISSUE THREAD

**Issue by Marjan202** [spring-projects/spring-integration-kafka#183]
Hi... I'm trying to record a INFO log using an integration:logging-channel-adapter. but, when it wants to take a new instance of java.util.Date(Long), catchExecutor in class "org.springframework.expression.spel.ast.ConstructorReference" returns java.util.Date(String) constructor so that it throws java.lang.IllegalArgumentException. my xml file:

    <integration:channel id="toBeDelayedChannel"/>
    <integration:router input-channel="toBeDelayedChannel"
                        expression="((headers['delayUntil'] ?: 0) > new java.util.Date().getTime()) ? 'delayed' : 'instant'">
        <integration:mapping value="delayed" channel="delayedNotificationChannel"/>
        <integration:mapping value="instant" channel="messageExpiratorChannel"/>
    </integration:router>

    <integration:channel id="delayedNotificationChannel">
        <integration:interceptors>
            <integration:wire-tap channel="logDelayedNotificationChannel"/>
        </integration:interceptors>
    </integration:channel>

    
    <integration:channel id="logDelayedNotificationChannel"/>
    <integration:logging-channel-adapter channel="logDelayedNotificationChannel"
                                         level="INFO"
                                         expression="'Delaying IVR, EventTypeName:' + headers['eventTypeName'] + ', Recipient:' + headers['recipient']  + ', ContactType:' + headers['contactType'] + ', ContactCode:' + headers['contactCode']+ ', Until: ' + new java.util.Date(headers['delayUntil'])"/>

**and the error:**

pid:12766 [ERROR] 2017-12-13T13:38:38.950 thread:[venEndpoint#0.container-1] eventId:[e130b705-3e70-42d6-bcc7-5fa8f37d0f0f] o.s.integration.handler.LoggingHandler:
        org.springframework.messaging.MessageHandlingException: error occurred in message handler [org.springframework.integration.handler.LoggingHandler#4]; nested exception is java.lang.IllegalArgumentException
        at org.springframework.integration.handler.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:139)
        at org.springframework.integration.dispatcher.AbstractDispatcher.tryOptimizedDispatch(AbstractDispatcher.java:116)
        at org.springframework.integration.dispatcher.UnicastingDispatcher.doDispatch(UnicastingDispatcher.java:147)
        at org.springframework.integration.dispatcher.UnicastingDispatcher.dispatch(UnicastingDispatcher.java:120)
        at org.springframework.integration.channel.AbstractSubscribableChannel.doSend(AbstractSubscribableChannel.java:77)
        at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:442)
        at org.springframework.integration.channel.interceptor.WireTap.preSend(WireTap.java:129)

**Comment by garyrussell** [comment]
You need to show the complete stack trace.

**Comment by Marjan202** [comment]
Hi Gary, Thanks for your answering. it is the complete stack trace:


 pid:12766 [DEBUG] 2017-12-13T13:38:38.948
thread:[venEndpoint#0.container-1]
eventId:[e130b705-3e70-42d6-bcc7-5fa8f37d0f0f]
o.s.integration.channel.PublishSubscribeChannel:
        preSend on channel 'errorChannel', message: ErrorMessage
[payload=org.springframework.messaging.MessageHandlingException: error
occurred in message handler
[org.springframework.integration.handler.LoggingHandler#4]; nested
exception is java.lang.IllegalArgumentException,
headers={timestamp=1513159718948, id=8d99b1a2-8c8f-4570-c357-f1397b7a220a}]

pid:12766 [ERROR] 2017-12-13T13:38:38.950
thread:[venEndpoint#0.container-1]
eventId:[e130b705-3e70-42d6-bcc7-5fa8f37d0f0f]
o.s.integration.handler.LoggingHandler:
        org.springframework.messaging.MessageHandlingException: error
occurred in message handler
[org.springframework.integration.handler.LoggingHandler#4]; nested
exception is java.lang.IllegalArgumentException
        at
org.springframework.integration.handler.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:139)
        at
org.springframework.integration.dispatcher.AbstractDispatcher.tryOptimizedDispatch(AbstractDispatcher.java:116)
        at
org.springframework.integration.dispatcher.UnicastingDispatcher.doDispatch(UnicastingDispatcher.java:147)
        at
org.springframework.integration.dispatcher.UnicastingDispatcher.dispatch(UnicastingDispatcher.java:120)
        at
org.springframework.integration.channel.AbstractSubscribableChannel.doSend(AbstractSubscribableChannel.java:77)
        at
org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:442)
        at
org.springframework.integration.channel.interceptor.WireTap.preSend(WireTap.java:129)
        at
org.springframework.integration.channel.AbstractMessageChannel$ChannelInterceptorList.preSend(AbstractMessageChannel.java:557)
        at
org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:434)
        at
org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:392)
        at
org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:115)
        at
org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:45)
        at
org.springframework.messaging.core.AbstractMessageSendingTemplate.send(AbstractMessageSendingTemplate.java:105)
        at
org.springframework.integration.router.AbstractMessageRouter.handleMessageInternal(AbstractMessageRouter.java:166)
        at
org.springframework.integration.handler.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:127)
        at
org.springframework.integration.dispatcher.AbstractDispatcher.tryOptimizedDispatch(AbstractDispatcher.java:116)
        at
org.springframework.integration.dispatcher.UnicastingDispatcher.doDispatch(UnicastingDispatcher.java:147)
        at
org.springframework.integration.dispatcher.UnicastingDispatcher.dispatch(UnicastingDispatcher.java:120)
        at
org.springframework.integration.channel.AbstractSubscribableChannel.doSend(AbstractSubscribableChannel.java:77)
        at
org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:442)
        at
org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:392)
        at
org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:115)
        at
org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:45)
        at
org.springframework.messaging.core.AbstractMessageSendingTemplate.send(AbstractMessageSendingTemplate.java:105)
        at
org.springframework.integration.handler.AbstractMessageProducingHandler.sendOutput(AbstractMessageProducingHandler.java:231)
        at
org.springframework.integration.handler.AbstractMessageProducingHandler.produceOutput(AbstractMessageProducingHandler.java:154)
        at
org.springframework.integration.handler.AbstractMessageProducingHandler.sendOutputs(AbstractMessageProducingHandler.java:102)
        at
org.springframework.integration.handler.AbstractReplyProducingMessageHandler.handleMessageInternal(AbstractReplyProducingMessageHandler.java:105)
        at
org.springframework.integration.handler.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:127)
        at
org.springframework.integration.dispatcher.AbstractDispatcher.tryOptimizedDispatch(AbstractDispatcher.java:116)
        at
org.springframework.integration.dispatcher.UnicastingDispatcher.doDispatch(UnicastingDispatcher.java:147)
        at
org.springframework.integration.dispatcher.UnicastingDispatcher.dispatch(UnicastingDispatcher.java:120)
        at
org.springframework.integration.channel.AbstractSubscribableChannel.doSend(AbstractSubscribableChannel.java:77)
        at
org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:442)
        at
org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:392)
        at
org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:115)
        at
org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:45)
        at
org.springframework.messaging.core.AbstractMessageSendingTemplate.send(AbstractMessageSendingTemplate.java:105)
        at
org.springframework.integration.router.AbstractMessageRouter.handleMessageInternal(AbstractMessageRouter.java:166)
        at
org.springframework.integration.handler.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:127)
        at
org.springframework.integration.dispatcher.AbstractDispatcher.tryOptimizedDispatch(AbstractDispatcher.java:116)
        at
org.springframework.integration.dispatcher.UnicastingDispatcher.doDispatch(UnicastingDispatcher.java:147)
        at
org.springframework.integration.dispatcher.UnicastingDispatcher.dispatch(UnicastingDispatcher.java:120)
        at
org.springframework.integration.channel.AbstractSubscribableChannel.doSend(AbstractSubscribableChannel.java:77)
        at
org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:442)
        at
org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:392)
        at
org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:115)
        at
org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:45)
        at
org.springframework.messaging.core.AbstractMessageSendingTemplate.send(AbstractMessageSendingTemplate.java:105)
        at
org.springframework.integration.handler.AbstractMessageProducingHandler.sendOutput(AbstractMessageProducingHandler.java:231)
        at
org.springframework.integration.handler.AbstractMessageProducingHandler.produceOutput(AbstractMessageProducingHandler.java:154)
        at
org.springframework.integration.handler.AbstractMessageProducingHandler.sendOutputs(AbstractMessageProducingHandler.java:102)
        at
org.springframework.integration.handler.AbstractReplyProducingMessageHandler.handleMessageInternal(AbstractReplyProducingMessageHandler.java:105)
        at
org.springframework.integration.handler.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:127)
        at
org.springframework.integration.dispatcher.AbstractDispatcher.tryOptimizedDispatch(AbstractDispatcher.java:116)
        at
org.springframework.integration.dispatcher.UnicastingDispatcher.doDispatch(UnicastingDispatcher.java:147)
        at
org.springframework.integration.dispatcher.UnicastingDispatcher.dispatch(UnicastingDispatcher.java:120)
        at
org.springframework.integration.channel.AbstractSubscribableChannel.doSend(AbstractSubscribableChannel.java:77)
        at
org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:442)
        at
org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:115)
        at
org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:45)
        at
org.springframework.messaging.core.AbstractMessageSendingTemplate.send(AbstractMessageSendingTemplate.java:105)
        at
org.springframework.messaging.core.AbstractMessageSendingTemplate.convertAndSend(AbstractMessageSendingTemplate.java:143)
        at
org.springframework.messaging.core.AbstractMessageSendingTemplate.convertAndSend(AbstractMessageSendingTemplate.java:135)
        at
org.springframework.integration.gateway.MessagingGatewaySupport.send(MessagingGatewaySupport.java:364)
        at
org.springframework.integration.jms.ChannelPublishingJmsMessageListener$GatewayDelegate.send(ChannelPublishingJmsMessageListener.java:504)
        at
org.springframework.integration.jms.ChannelPublishingJmsMessageListener.onMessage(ChannelPublishingJmsMessageListener.java:338)
        at
org.springframework.jms.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:721)
        at
org.springframework.jms.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:681)
        at
org.springframework.jms.listener.AbstractMessageListenerContainer.doExecuteListener(AbstractMessageListenerContainer.java:651)
        at
org.springframework.jms.listener.AbstractPollingMessageListenerContainer.doReceiveAndExecute(AbstractPollingMessageListenerContainer.java:313)
        at
org.springframework.jms.listener.AbstractPollingMessageListenerContainer.receiveAndExecute(AbstractPollingMessageListenerContainer.java:231)
        at
org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.invokeListener(DefaultMessageListenerContainer.java:1164)
        at
org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.executeOngoingLoop(DefaultMessageListenerContainer.java:1156)
        at
org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.run(DefaultMessageListenerContainer.java:1053)
        at java.lang.Thread.run(Thread.java:744)
Caused by: java.lang.IllegalArgumentException
        at java.util.Date.parse(Date.java:615)
        at java.util.Date.<init>(Date.java:272)
        at sun.reflect.GeneratedConstructorAccessor65.newInstance(Unknown
Source)
        at
sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
        at
org.springframework.expression.spel.support.ReflectiveConstructorExecutor.execute(ReflectiveConstructorExecutor.java:63)
        at
org.springframework.expression.spel.ast.ConstructorReference.createNewInstance(ConstructorReference.java:121)
        at
org.springframework.expression.spel.ast.ConstructorReference.getValueInternal(ConstructorReference.java:98)
        at
org.springframework.expression.spel.ast.OpPlus.getValueInternal(OpPlus.java:85)
        at
org.springframework.expression.spel.ast.SpelNodeImpl.getValue(SpelNodeImpl.java:120)
        at
org.springframework.expression.spel.standard.SpelExpression.getValue(SpelExpression.java:267)
        at
org.springframework.integration.handler.LoggingHandler.createLogMessage(LoggingHandler.java:175)
        at
org.springframework.integration.handler.LoggingHandler.handleMessageInternal(LoggingHandler.java:155)
        at
org.springframework.integration.handler.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:127)
        ... 75 more

**Comment by garyrussell** [comment]
```
Caused by: java.lang.IllegalArgumentException
        at java.util.Date.parse(Date.java:615)
        at java.util.Date.<init>(Date.java:272)
        at sun.reflect.GeneratedConstructorAccessor65.newInstance(Unknown
Source)
        at
sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
        at
```

That means that with `new java.util.Date(headers['delayUntil'])"`, `delayUntil` is a String - which means SpEL calls a deprecated constructor `Date(String)` which tries to parse a date from the String, which fails.

You need to set header to a `Long` value or use ``new java.util.Date(headers[Long.valueOf('delayUntil')])"`; then, SpEL will call `new Date(long)`.

**Comment by Marjan202** [comment]
really thanks for your answering...

Best Regards
