### ISSUE TITLE
Version 1.0.0.RC1 does not work with Kafka 0.8.2 on consumer side

### ISSUE THREAD

**Issue by mohitarora** [spring-projects/spring-integration-kafka#19]
I have 2 projects 

https://github.com/mohitarora/es-cqrs-example/tree/master/cart-command-services - This one produces messages and publishes to Kafka and works perfectly fine. 

https://github.com/mohitarora/es-cqrs-example/tree/master/cart-query-services - This one consumers messages published by previous project.

Both these projects uses Spring Boot. There is no error but the messages are never consumed. I also don't see any error but I am sure beans are not initialized.

Am i doing something wrong?

**Comment by artembilan** [comment]
@mohitarora , first of all thank you for paying attention to this project!

Let me ask for more info from you:
1. Let us know how it works with 1.0.0.RELEASE
2. Why do you make such a conclusion: " but I am sure beans are not initialized." ? Is there anything which does not say that it has been started or anything similar? Can't you access to some beans from your app?
3. Have you tried to send messages to the Kafka topic directly without that publisher application ?

Note: we have plans to upgrade to the Kafka `0.8.2` including new features, but it will be for our `1.1.0` version. So, to be honest we haven't tested our solution against Kafka 0.8.2 :smile:

**Comment by mohitarora** [comment]
I upgraded to 1.0.0.RELEASE, no luck

Producer is still working fine (https://github.com/mohitarora/es-cqrs-example/blob/master/cart-command-services/src/main/resources/kafka.xml)

Consumer is not (https://github.com/mohitarora/es-cqrs-example/blob/master/cart-query-services/src/main/resources/kafka.xml)

My guess is I am doing something stupid on consumer side, Can you please check my kafka.xml on consumer side.

I tried sending messages to Kafka topic directly without producer application, still no luck.

Why i say the beans are not initialized. I have a break point in line 58 of KafkaConsumerContext.java and when i run in debug mode, control never reaches there. I must re-word, beans are getting initialized else application will not start but they are not getting correctly initialized. I don't see any kafka related stuff on spring boot application startup logs.

**Comment by artembilan** [comment]
@mohitarora , can you confirm that you app works well with `Kafka-0.8.1.1`?
And we go ahead to seek an issue with 0.8.2 compatibility.
Thank you very much!

**Comment by mohitarora** [comment]
This issue is resolved with 1.1.1.RELEASE
