### ISSUE TITLE
Expose additional lifecycle (consumer/producer) callbacks

### ISSUE THREAD

**Issue by olegz** [spring-projects/spring-integration-kafka#198]
While working on https://github.com/spring-cloud/spring-cloud-stream/issues/1055 I've realized that at the moment si-kafka (KafkaMessageDrivenChannelAdapter) doesn't expose the appropriate callbacks to perform `pause/resume` etc.
Could you please add it

**Comment by artembilan** [comment]
This won't be enough here. We need `pause()/resume()` on the container contract - in Spring Kafka.
