### ISSUE TITLE
Plan for 2.2.0.RELEASE?

### ISSUE THREAD

**Issue by jmanning2k** [spring-projects/spring-integration-kafka#201]
For Kafka 0.10.2.x, the compatibility matrix at http://projects.spring.io/spring-kafka/ has: spring-kafka=1.2.x and spring-integration-kafka 2.2.x.

However, there is no RELEASE build of spring-integration-kafka 2.2.0, only M1 and RC1. This means it is only available via the spring-milestones repository, and not available from maven central.

Can the latest RC be promoted to a GA build, so there is a complete stack compatible with Kafka 0.10.2.x?

**Comment by artembilan** [comment]
I think that's just an omission and we have to release it ASAP.
There is nothing to stop us to do that.

WDYT, @garyrussell ? I can upgrade to the latest reasonable dependencies and push RELEASE button.

@jmanning2k , thank you very much for a good catch!

**Comment by garyrussell** [comment]
Sure sounds good - must have fallen through the cracks. Thanks @artembilan

**Comment by garyrussell** [comment]
That said, I would recommend getting onto at least Spring Kafka 1.3.x as soon as possible; it has a much simpler threading model, enabled by KIP-62, and the newer clients (0.11.x.x, 1.0.0) can still talk to an 0.10.2.x broker if you're stuck on that broker version.

**Comment by artembilan** [comment]
> can still talk to an 0.10.2.x broker if you're stuck on that broker version

Ah! That's good point! But we still need to provide some versions exclusion/inclusion dancing.

Anyway - releasing `2.2.0 GA`...

**Comment by artembilan** [comment]
Fixed via https://github.com/spring-projects/spring-integration-kafka/commit/56dd6c6719842fe7a6514aa607d24867bc04a508

**Comment by artembilan** [comment]
The `2.2.0.RELEASE` has reached Maven Central: https://bintray.com/spring/jars/spring-integration-kafka/2.2.0.RELEASE#central.
