### ISSUE TITLE
Missing spring-integration-kafka.xsd for latest release

### ISSUE THREAD

**Issue by kcturner123** [spring-projects/spring-integration-kafka#207]
The examples include using XML configuration, but the example for KafkaMessageDrivenChannelAdapter will not work because the appropriate xsd cannot be found. The only version I can find is 1.0 which does not include the mode attribute for message-driven-channel-adapter.

**Comment by artembilan** [comment]
I have just downloaded jar from here: https://search.maven.org/#artifactdetails%7Corg.springframework.integration%7Cspring-integration-kafka%7C3.0.3.RELEASE%7Cjar and three is indeed a `org\springframework\integration\kafka\config\spring-integration-kafka-3.0.xsd` file there.

I somehow think that you use Eclipse without Spring Nature, so it tries to find XSD from the Internet.
Please, consider to use Spring-aware IDE, e.g. STS: https://spring.io/tools

**Comment by kcturner123** [comment]
I am using STS, but I forgot to add the spring-integration-kafka artifact to the POM on my latest project. Occupational hazard of being an architect and not coding regularly. Thanks for jogging my brain.
