### ISSUE TITLE
KafkaMessageSource and concurrency

### ISSUE THREAD

**Issue by bruto0** [spring-projects/spring-integration-kafka#211]
If you disable autoack in AcknowledgmentCallbackFactory and ack/requeue offsets in a different thread from the one poller is operating on, all sorts of things become possible here under sufficient load:

				Set<KafkaAckInfo<K, V>> candidates = this.ackInfo.getOffsets().get(this.ackInfo.getTopicPartition());
				KafkaAckInfo<K, V> ackInfo = null;
    				if (candidates.iterator().next().equals(this.ackInfo)) {
					// see if there are any pending acks for higher offsets
					List<KafkaAckInfo<K, V>> toCommit = new ArrayList<>();
					for (KafkaAckInfo<K, V> info : candidates) {

ConcurrentModificationException, NoSuchElementException

Also, acknowledged flag is set in the finally block of KafkaAckCallback.acknowledge unconditionally, although in case of ConcurrentModificationException you likely want to try ack'ing the offset again

And while we're at it, it'd be nice to have an ability to ack a bunch of offsets belonging to the same partition without sync'ing on the consumerMonitor for each one, but you'd have to expose KafkaMessageSource from the inbound channel adapter for that to work

**Comment by bruto0** [comment]
should probably put this:

		KafkaAckInfo<K, V> ackInfo = new KafkaAckInfoImpl(record, topicPartition);
		AcknowledgmentCallback ackCallback = this.ackCallbackFactory.createCallback(ackInfo);
		this.inflightRecords.computeIfAbsent(topicPartition, tp -> new TreeSet<>()).add(ackInfo);

inside the synchronized block

**Comment by garyrussell** [comment]
>ack/requeue offsets in a different thread

While thread-safety should be fixed; acking like that probably won't do what you need. If you hand the message off to another thread, the acks might be processed out of order, which is probably not what you want.

With Kafka, only a log offset is committed, each message is not "ack'd" per se. So if the record at offset 2 is ack'd first, the record at offset 1 is also "ack'd". Worse, when offset 1 is later committed (and let's say the app is restarted), you will get the record at offset 2 again.

**Comment by garyrussell** [comment]
>With Kafka, only a log offset is committed, each message is not "ack'd" per se. So if the record at offset 2 is ack'd first, the record at offset 1 is also "ack'd". Worse, when offset 1 is later committed (and let's say the app is restarted), you will get the record at offset 2 again.

Actually, I forgot; we added code to defer "future" acks and only commit them when the "gaps" are filled in.

I am fixing the concurrency now...
