### ISSUE TITLE
Enhancement: Graceful shutdown of async producers

### ISSUE THREAD

**Issue by cydergoth** [spring-projects/spring-integration-kafka#235]
**Affects Version(s):** \<Spring Integration version>

---

As a message producing application, I should like to gracefully shutdown an async message producer (e.g. Kafka via Spring Cloud Streams Kafka Binder which uses **KafkaTemplate**) with the assurance that messages pending on the async send queue have been successfully ack-ed by Kafka. I should also like to be able to defer shutdown until the other parts of the application have ceased to source messages in their beans. KafkaTemplate exposes the flush() method which looks encouraging, but is not exposed higher up or called in the unbind() method.

For example, suppose I have a REST -> Kafka gateway which takes a batch of data in and dispatches a Kafka message for each datum in the batch. Halfway through processing a REST request, a shutdown signal is received. Using the [Tomcat Graceful Shutdown](https://dzone.com/articles/graceful-shutdown-spring-boot-applications) the application pauses the Tomcat connector. At this point no new connections are accepted by Tomcat, however we permit the existing REST call to continue processing. We wish to keep the message producer running during this time to ensure that the rest (sic) of the data messages are correctly dispatched. Once all the data messages have been dispatched the REST call returns and we are now safe to shutdown Tomcat. The message producer, however, may have accepted messages for dispatch which are pending on the async message queue and have not been actually sent to Kafka. At this point, we should like to wait for that queue to drain and all the Acks from Kafka are received before shutting down the message producer.

**Comment by cydergoth** [comment]
Thanks @garyrussell, this will definitely help. How may we defer calling flush() until we have processed the existing messages in the system - Do we need to ensure that the teardown of the Kafka producer only occurs after the teardown of tomcat by using bean ordering? Or is there a shutdown hook we can intercept to pause shutdown until our message generation is completed?

**Comment by garyrussell** [comment]
@cydergoth While it doesn't have a callback mechanism, the `IntegrationMBeanExporter` has an orderly shutdown mechanism [described here](https://docs.spring.io/spring-integration/reference/html/#jmx-shutdown).

Alternatively, you can monitor the `sendCount` property of the output channel and wait for it to quiesce.

**Comment by cydergoth** [comment]
Thanks for the helpful advice!
