### ISSUE TITLE
jacksonVersion on master regressed from 3.1.4.RELEASE

### ISSUE THREAD

**Issue by jmax01** [spring-projects/spring-integration-kafka#274]
jacksonVersion on master regressed from 3.1.4.RELEASE

3.1.4.RELEASE: https://github.com/spring-projects/spring-integration-kafka/blob/8c98cd948fa245272382a96f05c87b25add96663/build.gradle#L57

vs

master: https://github.com/spring-projects/spring-integration-kafka/blob/eaa8f5f7ba22502d994398a6763053772f3744e9/build.gradle#L58

**Comment by garyrussell** [comment]
Thanks, but it wasn't really a "regression" as such; we just hadn't gotten around to updating it on master.

**Comment by jmax01** [comment]
> Thanks, but it wasn't really a "regression" as such; we just hadn't gotten around to updating it on master.

I was careful to not call it a "regression" but to say it "regressed".
I did this in case there was any tooling that would be triggered by "regression".
