### ISSUE TITLE
Upgrade to Jackson 2.10

### ISSUE THREAD

**Issue by tomvandenberge** [spring-projects/spring-integration-kafka#286]
I'm looking into adding support for configuring the header mapper for an outbound channel adapter in XML; it seems to be missing.

I've cloned the repository, but I can't get the unit tests running ("gradlew test"). They all fail with "java.lang.NoClassDefFoundError: com/fasterxml/jackson/databind/json/JsonMapper"

I guess I'm doing something wrong?

**Comment by artembilan** [comment]
I have just pushed an upgrade to Jackson `2.10` and all tests passes for me.

Thank you for your willing to contribute; looking forward for your PR(s) !
