### ISSUE TITLE
Support OffsetManagment "kafka"

### ISSUE THREAD

**Issue by smil2k** [spring-projects/spring-integration-kafka#49]
Since 0.8.2, Kafka servers are offering offset management feature via OffsetRequest/OffsetCommit messages. 

Consumer should have an option to use this service instead of emulating it.

**Comment by mbogoevici** [comment]
Makes sense. We should create a JIRA item for it.

**Comment by garyrussell** [comment]
[Moved to JIRA](https://jira.spring.io/browse/INTEXT-177).

@smil2k please track/watch there.

**Comment by artembilan** [comment]
Closed in favor of appropriate JIRA
