### ISSUE TITLE
KafkaMessageListenerContainer fetchTaskExecutor

### ISSUE THREAD

**Issue by idcmp** [spring-projects/spring-integration-kafka#51]
It looks like FetchTask.run is done 1 per Broker, so by default the maximum # of threads you would need for fetch tasks is the # of brokers you're consuming from.

However, in KMLC.start() a default fetchTaskExecutor is created using partitionsByBrokerMap.size() which would yield a thread pool the size of the # of partitions. 

Did you really mean something like partitionsByBrokerMap.keys().size()?

**Comment by mbogoevici** [comment]
@idcmp Good catch. Thanks.

**Comment by artembilan** [comment]
The PR #52 has been merged
