### ISSUE TITLE
Potentially ignored failed message delivery

### ISSUE THREAD

**Issue by sharpnk** [spring-projects/spring-integration-kafka#62]
In `KafkaProducerMessageHandler.handleMessageInternal(Message<?> message)`, the message is fired to Kafka broker with this call:

`this.kafkaProducerContext.send(topic, partitionId, messageKey, message.getPayload());
KafkaProducer.send(ProducerRecord<K,V> record) `

It returns a `Future<RecordMetadata>` object, but for some reason the response is ignored. I assume it's because the intention is to assume the request will be successful and let any exception bubble up to the caller later on. However, when I look into the code for `KafkaProducer`, it actually silently swallow any `ApiException` and return a `FutureFailure` object instead of directly throwing exceptions.

I am curious that in this case, without checking the `Future` response from the KafkaProducerContext, would we run the risk of ignoring an failed message delivery to Kafka broker?

**Comment by artembilan** [comment]
I think you are correct and we definitely should fix that.

From my perspective the fix should look like `KafkaIntegrationEvent` which is emitted on the `Future.get()` result (or its Exception) *asynchronously*, not directly to the caller Thread.

I don't like to block the caller just because the Kafka async nature.

Any other ideas are welcome!

Thank you for pointing that out, @sharpnk, anyway !

**Comment by mbogoevici** [comment]
The best solution here would be to use a callback. Should add this to the next version.

**Comment by VikasJindal84** [comment]
Is there any way that i can check for exception till fix is available . In our case , we want to store messages in temp location ,if kafka broker is not available and re-try to send ,after some time.

**Comment by mbogoevici** [comment]
A fix should be available in the master branch early next week.

**Comment by mbogoevici** [comment]
The Kafka API itself throws no exception, only the callback is available.

**Comment by VikasJindal84** [comment]
Hi Marius ,

Thanks for sharing information . If a fix is available in next week , then it will be quite helpful to us . Is there any issue is available for keeping watch for code commit of this fix  ? Basically i want to use it as soon as it available.

**Comment by mbogoevici** [comment]
Hi Vikas, I've added this https://jira.spring.io/browse/INTEXT-203 - you can try following that or even this issue.

**Comment by mbogoevici** [comment]
Added this for supporting notifications on acknowledgment/failure https://github.com/spring-projects/spring-integration-kafka/pull/80

**Comment by VikasJindal84** [comment]
Thanks Marius ,

I am using https://github.com/spring-cloud/spring-cloud-stream/tree/master/spring-cloud-stream-samples/source sample to produce messages , How can i register ProducerListener in this case ?

**Comment by artembilan** [comment]
Fixed with the https://github.com/spring-projects/spring-integration-kafka/commit/325d0b294c825252f5313bd9696229d198b0d38e.

`ProducerListener` is a part of `ProducerConfiguration` and can be specified as a `ref` attribute on the `<producer-configuration>`. 
Closed as a valuable fix.
