### ISSUE TITLE
Issue with ConsumerConfiguration.receive method.

### ISSUE THREAD

**Issue by abhijith-prabhakar** [spring-projects/spring-integration-kafka#63]
Hi,

I see an major issue on ConsumerConfiguration.recieve() method.  If maxMessages is set to a very high value and no of messages in kafka topic is less, then while loop in this method will keep running until maxMessages value is hit.  It will never exit until that many number of messages arrived.  For ex: I have set maxMessages value as 5000 and there are 500 messages put in that topic.  I never get control back since this while loop keeps looping.  The only way I could get back the control is to keep consumer time out very less.  Please let me know if I am missing something.

```
public Map<String, Map<Integer, List<Object>>> receive() {
		count = messageLeftOverTracker.getCurrentCount();
		final Object lock = new Object();

		final List<Callable<List<MessageAndMetadata<K, V>>>> tasks = new LinkedList<Callable<List<MessageAndMetadata<K, V>>>>();

		for (final List<KafkaStream<K, V>> streams : createConsumerMessageStreams()) {
			for (final KafkaStream<K, V> stream : streams) {
				tasks.add(new Callable<List<MessageAndMetadata<K, V>>>() {
					@Override
					public List<MessageAndMetadata<K, V>> call() throws Exception {
						final List<MessageAndMetadata<K, V>> rawMessages = new ArrayList<MessageAndMetadata<K, V>>();
						try {
							while (count < maxMessages) {
								final MessageAndMetadata<K, V> messageAndMetadata = stream.iterator().next();
								synchronized (lock) {
									if (count < maxMessages) {
										rawMessages.add(messageAndMetadata);
										count++;
									}
									else {
										messageLeftOverTracker.addMessageAndMetadata(messageAndMetadata);
									}
								}
							}
						}
						catch (ConsumerTimeoutException cte) {
							LOGGER.debug("Consumer timed out");
						}
						return rawMessages;
					}
				});
			}
		}
		return executeTasks(tasks);
	}
```

**Comment by artembilan** [comment]
Hello, @abhijith-prabhakar !

Unfortunately, no: you haven't missed anything...
It's a know bug (https://jira.spring.io/browse/INTEXT-139) and looks like we definitely should fix it.

Contribution is welcome :smile:

**Comment by mbogoevici** [comment]
I would suggest using the KafkaMessageListenerContainer instead.

**Comment by artembilan** [comment]
@mbogoevici ,

thank you for reaching us!
It is really a bit difficult to be on the aboard without expert hand :smile: .

Don't you say with your recommendation that we should deprecate our High Level Consumer Adapter?
Or should we revise it one more time and re-write other way?

Thanks!

**Comment by mbogoevici** [comment]
Yes, I think we should do that in the 1.x line. In fact, I think that version 2.0 should be based on 0.9 and have the entire High Level Consumer Adapter removed (as the API is deprecated). We can use the new consumer adapter which will be production-grade for 0.9. Unfortunately transition isn't easy as there are some older implementations out there that use the 0.8 APIs ...

**Comment by artembilan** [comment]
@mbogoevici , let's fix this issue as a `@Deprecated` in version `1.3`!
I just mean that the fix isn't so simple for the API which will be removed in the future...

**Comment by mbogoevici** [comment]
@artembilan I agree, the whole high lever consumer stuff can be deprecated in 1.3.

**Comment by artembilan** [comment]
OK. Would you mind sharing the Kafka ticket (or some other note) where they announce the deprecation and removal eventually?
Thanks

**Comment by mbogoevici** [comment]
Would have to dig it up, but we can deprecate our own high level consumer stuff anyway since we have the simple consumer-based message listener container, I believe?

**Comment by artembilan** [comment]
Yes, that's fine. Quoting some guy from the Internet:

> Never mind – I went through the Kafka high level consumer source code, and I came to a conclusion that it is not possible to create high level consumers on per-partition basis like I asked above. To do that I must use SimpleConsumer. ... On the same time, the trade-off is I do not have control over from which partition each consumer retrieves data (only the SimpleConsumer API gives this level of control).

And an answer for him from Gwen Shapira:

> True. High level API doesn’t let you choose which partition each consumer reads.

**Comment by mbogoevici** [comment]
Yes, that's the reason why we have the SimpleConsumer API anyway. Plus a few others (lack of offset control for example).

**Comment by artembilan** [comment]
:+1: 
Will be PR'ed soon.

**Comment by artembilan** [comment]
Closed in favor of https://jira.spring.io/browse/INTEXT-139
