### ISSUE TITLE
Consumer time out and zookeeper connect

### ISSUE THREAD

**Issue by abhijith-prabhakar** [spring-projects/spring-integration-kafka#64]
Hi,

I am very confused on where to set consumer timeout.  Please find below how I create consumer context.  The only way I could get this work was to provide zookeeper.connect and consumer.timeout.ms directly to ConsumerConfig via Properties.  Also not sure what ConsumerMetadata.setConsumerTimeout does.

kafkaConsumerContext.setZookeeperConnect and kafkaConsumerContext.setConsumerTimeout has no effect at all.  Please let me know if I am missing something.

```
 private KafkaConsumerContext kafkaConsumerContext() throws IOException {
        KafkaConsumerContext kafkaConsumerContext = new KafkaConsumerContext();
        Map<String, ConsumerConfiguration> map = new HashMap<>();

        ConsumerMetadata consumerMetadata = new ConsumerMetadata();
        consumerMetadata.setGroupId(groupId);
        consumerMetadata.setValueDecoder(new AvroSpecificDatumBackedKafkaDecoder(User.class));
        consumerMetadata.setKeyDecoder(new AvroReflectDatumBackedKafkaDecoder(String.class));

        Map<String, Integer> topicStreamMap = new HashMap<>();
        topicStreamMap.put(topic, 1);
        consumerMetadata.setTopicStreamMap(topicStreamMap);
        consumerMetadata.setConsumerTimeout(consumerTimeout);

        Properties properties = new Properties();
        properties.put("zookeeper.connect", zookeeper);
        properties.put("group.id", groupId);
        properties.put("consumer.timeout.ms", consumerTimeout);
        properties.putAll(getProducerConfigProps());
        ConsumerConfig consumerConfig = new ConsumerConfig(properties);
        ConsumerConnectionProvider consumerConnectionProvider = new ConsumerConnectionProvider(consumerConfig);

        ConsumerConfiguration consumerConfiguration = new ConsumerConfiguration(consumerMetadata,
                consumerConnectionProvider, new MessageLeftOverTracker());
        //NOTE:  Max messages is what determines how many messages to be picked together.  Default is 1.
        consumerConfiguration.setMaxMessages(5000);
        //Same as producer config, key to this map does not have any meaning.  You can give any key name.
        map.put("config", consumerConfiguration);

        kafkaConsumerContext.setConsumerConfigurations(map);
        kafkaConsumerContext.setConsumerTimeout(consumerTimeout);

//        kafkaConsumerContext.setZookeeperConnect(new ZookeeperConnect("10.24.72.103:2181"));
        return kafkaConsumerContext;

    }
```

**Comment by artembilan** [comment]
Hello, @abhijith-prabhakar !

And sorry for the delay.

Yes, I agree with you that there is some issues and a mess around this `Consumer` stuff.
Consider to use `ConsumerConfigFactoryBean` instead of direct `ConsumerConfig`.
The `ConsumerMetadata.setConsumerTimeout` has affect, BTW.

From other side consider to use Spring Integration Java DSL on the matter: https://spring.io/blog/2015/04/15/spring-integration-java-dsl-1-1-m1-is-available.

You can find there `Kafka` Namespace Factory, which allows you to simplify the configuration.

With this one I'd suggest to go ahead with the PR, if you'd like to contribute!

**Comment by artembilan** [comment]
Closed with the workaround and as part of the API which will be deprecated soon:
https://jira.spring.io/browse/INTEXT-139.
