### ISSUE TITLE
Simple API equivalent to JmsTemplate

### ISSUE THREAD

**Issue by efenderbosch** [spring-projects/spring-integration-kafka#74]
I'm looking for a simple way to send a message to a Topic and subscribe to that Topic.

All the examples I've read are inherently complex. Is there no simple API similar to JmsTemplate?

My goal is to replace ActiveMQ w/ Kafka in a Spring Boot project, but keep it as simple as possible. Right now I'm creating ZookeeperConfiguration and ConnectionFactory beans from application.yml, but don't really know where to go from here.

Ideally, I'd like to stay away from any XML based configuration. Any ideas or pointers would be appreciated.

**Comment by garyrussell** [comment]
Yes, there's a [KafkaTemplate](https://github.com/spring-projects/spring-integration-kafka/blob/master/src/main/java/org/springframework/integration/kafka/core/KafkaTemplate.java).

**Comment by efenderbosch** [comment]
Can a FetchRequest be used for both a send and receive?

**Comment by garyrussell** [comment]
It currently only supports receive operations; the intent is to eventually flush it out to support other operations.

You can easily wire in a Kafka outbound channel adapter into your boot app - see [the sample here](https://github.com/spring-projects/spring-integration-samples/tree/master/basic/kafka) (which is a boot app).

**Comment by efenderbosch** [comment]
That example is much better. Thank you. I only found the example from the readme in this project and on the spring.io blog.

**Comment by garyrussell** [comment]
Thanks; I added a link to that sample to the README,
