### ISSUE TITLE
Update kafkaVersion to 0.8.2.2

### ISSUE THREAD

**Issue by magiccrafter** [spring-projects/spring-integration-kafka#75]
Hi team,

First thanks for all the good work you do in spring-integration-kafka project and in spring-integration at all.
I've faced this issue (https://issues.apache.org/jira/browse/KAFKA-2308) and I would kindly ask you to update the kafkaVersion from '0.8.2.1' to '0.8.2.2'. It is not casing issues if I explicitly define the kafka dependency to 0.8.2.2, which I do, so it is more like nice to have.

Thanks again

**Comment by artembilan** [comment]
Done. 
The upgrade will be available since the next `1.2.2` release. Probably the next week.

Thank you for the feedback!
