### ISSUE TITLE
KafkaMessageListenerContainer does not connect to new unknown parttions

### ISSUE THREAD

**Issue by vladislav-sidorovich** [spring-projects/spring-integration-kafka#77]
Similarly to #70 if topic will increase count of  partitions at runtime Spring dose not consuming messages from new partitions.

Probably 
KafkaMessageListenerContainer use newFixedThreadPool for FetchTasks and new tasks never runs, maybe just newCachedThreadPool can fix this problem

The easiest way to reproduce:

* Create a Kafka cluster with 2 brokers
* Create a topic with 1 partition
* Configure Spring to consume that topic
* Alter topic: --alter --partitions 4
* Spring lose some messages and then stop consuming

**Comment by mbogoevici** [comment]
Hi @vladislav-sidorovich,

We currently do not update the metadata for a running client. Planning to make this change in v 1.2.2, which is due next week.

Thanks for the interest,
Marius

**Comment by vladislav-sidorovich** [comment]
Hello @mbogoevici 
any news about v 1.2.2?

**Comment by mbogoevici** [comment]
Hi @vladislav-sidorovich,

We've intended to have a 1.3.0.RC and a 1.2.2 next week, but decided to postpone until early next, in order to fix a few more issues.

Cheers,
Marius

**Comment by mbogoevici** [comment]
Hi @vladislav-sidorovich,

An update on this: we decided to release 1.3 without supporting dynamic detection of new partitions.

For solving this, now that Kafka 0.9 RC has been released, we will support it as part of integrating with the new client library in Spring Integration Kafka 2.0. 

Hope this helps,
Marius

**Comment by artembilan** [comment]
Having Spring Integration Kafka 2.0 GA [released](https://spring.io/blog/2016/07/04/spring-for-apache-kafka-1-0-and-spring-integration-kafka-2-0-go-ga) and with a new `ConsumerRebalanceListener` from Kafka 0.9 aboard with the `KafkaMessageListenerContainer` underneath, consider this issue as fixed.
