### ISSUE TITLE
partitioner configuration in producer context not working

### ISSUE THREAD

**Issue by rrs120486** [spring-projects/spring-integration-kafka#84]
In README its mentioned :
`partitioner : Custom implementation of a Kafka Partitioner interface.`

But looks like partitioner config has been deprecated instead its advisable to use KafkaHeader for PartitionId.

```
log.warn("'partitioner' is a deprecated option. Use the 'kafka_partitionId' message header or " +
							"the partition argument in the send() or convertAndSend() methods");
```
By any chance we can still use that config for producer as its more convenient than to assign partitionid individually for each message.

**Comment by mbogoevici** [comment]
Hi @rrs120486,

It will be supported for Kafka 1.3, but it is deprecated, since it is part of the old Kafka client API. 

Thanks,
Marius

**Comment by artembilan** [comment]
Note: you can still use your `partition` algorithm, but as not a `kafka.producer.Partitioner` to avoid the deprecated API removal, but its reference to the `partition-id-expression`.

Will be PR soon about improvement on the matter.

**Comment by artembilan** [comment]
Also, see the fix https://github.com/spring-projects/spring-integration-kafka/commit/4786b64f51443ff788e8985fbbf12857cf435378
