### ISSUE TITLE
Scala 2.11 support

### ISSUE THREAD

**Issue by lesongjia** [spring-projects/spring-integration-kafka#88]
Hi,

Is there a timeline when Scala 2.11 will be supported? Thanks

**Comment by lesongjia** [comment]
I am new to Kafka and Spring Integration Kafka. Currently, I force excluding Kafka_2.10 in Spring Integration Kafka and add Kafka_2.11. It worked with no problem for now. But I am a little concerned that if anything is not compatible in the future. 

Any thoughts or suggestions will be much appreciated!

**Comment by mbogoevici** [comment]
Hi,

Trying to understand the requirement for Scala 2.11. Are you embedding this in a Scala application?

**Comment by lesongjia** [comment]
Thanks for your quick response. 

Our application is currently using DiUS/pact-jvm which requires Scala 2.11 or higher version for PACT. We are now trying to integrate with Kafka using Spring Integration Kafka. And the Scala version is not compatible. Hope this helps to understand.

**Comment by mbogoevici** [comment]
Hi,

Thanks for the explanation! I think replacing the kafka version should be safe for now, since our reliance on Scala is limited to that. 

For 2.0 we plan to use Kafka 0.9 and its client libraries which do not rely on Scala at all.

Cheers,
Marius

**Comment by lesongjia** [comment]
Cool! Thanks, btw, when will be 2.0 released? We are looking to move to Kafka 0.9 as well when it is ready.

**Comment by mbogoevici** [comment]
We're still working on a timeline for it, trying to release 1.3 first to take care of a few issue.

**Comment by lesongjia** [comment]
Got it! Thanks for your help, mbogoevici.
