### ISSUE TITLE
How can i start the embedded Kafka server to unit test

### ISSUE THREAD

**Issue by ashishsoni** [spring-projects/spring-integration-kafka#91]

**Comment by artembilan** [comment]
The [Spring-Kafka](https://github.com/spring-projects/spring-kafka) project has been just released in its `1.0.0.M1` release and Spring Integration Kafka 2.0 has been moved to that code based already.

That project provides `KafkaEmbedded` JUnit `Rule` which can be used from the test config together with the `KafkaTestUtils` to populate `producer` or `consumer` properties for the `DefaultKafkaConsumerFactory/DefaultKafkaProducerFactory` beans for the target `KafkaTemplea` and/or `MessageListenerContainer` beans.

Consider the issue as fixed.
Feel free to reopen or open a new one in the appropriate project.
