### ISSUE TITLE
How to Override the topic Name 

### ISSUE THREAD

**Issue by ashishsoni** [spring-projects/spring-integration-kafka#92]
I am providing the topic name as below but i see the message still posted to the topic configure in the XML file

Please let me know what is missing 
````
@Inject
    MessageChannel inputToKafka;


    public void sendMessageToKafka(String message) {
        inputToKafka.send(
                MessageBuilder.withPayload(message)
                        .setHeader(KafkaHeaders.MESSAGE_KEY, "1")
                        .setHeader(KafkaHeaders.TOPIC, "newtopic")
                        .build());
   }
````
XML File 

````
<int-kafka:producer-context id="kafkaProducerContext" >
        <int-kafka:producer-configurations>
            <int-kafka:producer-configuration broker-list="host:6667"            		   
                       key-class-type="java.lang.String"
                       value-class-type="java.lang.String"
                       topic="sample"
                       value-serializer="kafkaSerializer"
                       key-serializer="kafkaSerializer"
                       compression-type="none"/>
        </int-kafka:producer-configurations>
    </int-kafka:producer-context>
````

**Comment by mbogoevici** [comment]
What version of Spring Integration Kafka are you using? Can you try using `1.3.0.RELEASE`, please?

**Comment by ashishsoni** [comment]
Just Changed it and tried but no luck i can see message still goes to topic configured in XML

**Comment by mbogoevici** [comment]
Do you mind sharing your project?

**Comment by ashishsoni** [comment]
try download from here

https://drive.google.com/file/d/0B--LI-1OKy_NbDl2R3FsMnhCb3c/view?usp=sharing

**Comment by garyrussell** [comment]
//TODO revise the headers fallback behavior in favor of just expression

Looks like the XML wins.

Replace `topic="sample"` with

    topic-expression="headers['kafka_topic'] ?: 'sample'"

**Comment by mbogoevici** [comment]
Yeah, I don't think this is expected behaviour though. We should either remove OOTB header support or have it have maximum precedence.

**Comment by garyrussell** [comment]
Yes; the issue is, internally, the adapter can't tell if the expression was set as `topic` or `topic-expression`. I suppose it could detect a `LiteralExpression` but that would be a bit brittle.

OTOH, we probably do need to support the scenario where the headers are ignored in favor of a configured topic and/or expression, to avoid leakage from an inbound adapter, so maybe the status quo is ok (most flexible).

I am not sure we want to remove header support for when no `topic(-expression)?` is provided. IIRC, that was originally the only option.

What we usually do for cases like that is make the default expression `headers['kafka_topic']` rather than having explicit code like there is there now.

**Comment by mbogoevici** [comment]
I think we need to simplify this drastically, because if there's no `topic` and no header, the producer will fall back to the topic configured in the sole configuration of `KafkaProducerContext`, so there is still some kind of (non-obvious) default.

**Comment by mbogoevici** [comment]
@garyrussell 's is the correct one, under the circumstances.

**Comment by artembilan** [comment]
The current logic is like this:
```
String topic = this.topicExpression != null ?
			this.topicExpression.getValue(this.evaluationContext, message, String.class)
			: message.getHeaders().get(KafkaHeaders.TOPIC, String.class);

Assert.state(StringUtils.hasText(topic), "The 'topic' can not be empty or null");
```
So, if there is a requirement to obtain a `topic` with the current message context, the `topicExpression` must be configured respectively.
