### ISSUE TITLE
Integration with new KafkaConsumer in Kafka 0.9

### ISSUE THREAD

**Issue by hw6** [spring-projects/spring-integration-kafka#93]
Is there any plan to integrate the new  KafkaConsumer which was introduced recently in Kafka 0.9?

**Comment by garyrussell** [comment]
Yes; we are planning on moving to the new 0.9 consumer in the next release (2.0).

**Comment by Blackbaud-KevinHutson** [comment]
That's great news as we will be using 0.9 in our initial rollout and would love to keep using spring-integration-kafka. Do you have a projected timeline for 2.0? I know it's difficult to project release dates. We're just looking for a ballpark estimate. :-)

**Comment by garyrussell** [comment]
We haven't really sized the effort yet so whatever I say here is meaningless; but unless there are big surprises, I would think we could have a milestone release early in the New Year.

Of course, [contributions](https://github.com/spring-projects/spring-integration/blob/master/CONTRIBUTING.md) are always welcome!

**Comment by Blackbaud-KevinHutson** [comment]
Thanks for the info! I'll keep that in mind.

**Comment by nucknorris** [comment]
Any estimation on when the next release (2.0) is going to be released?

**Comment by garyrussell** [comment]
We should have some idea in a couple of weeks.

**Comment by yangl** [comment]
0.9.0.1 is the latest release. The current stable version is 0.9.0.1.
this is time to upgrade to support 0.9.X

**Comment by mbogoevici** [comment]
Hi @yangl,

The upgrade to the 0.9.X will support 0.9.0.1 indeed.

**Comment by garyrussell** [comment]
Yes; already working with 0.9.0.1.

As an update for the "when" questions ( @nucknorris , @Blackbaud-KevinHutson , @hw6 ), based on my current efforts, I expect we'll have a milestone release for 2.0 in the next week or so; maybe sooner.

**Comment by artembilan** [comment]
The Spring Kafka project has been has been born: https://github.com/spring-projects/spring-kafka.

Spring Integration Kafka 2.0 will be based on that.

Leaving open until the appropriate PR (#107)  will be merged.

**Comment by artembilan** [comment]
I guess this issue has been just fixed with the #109 and its commits.

**Comment by garyrussell** [comment]
We should leave this open at least until we publish a milestone.

**Comment by garyrussell** [comment]
Please note that the first milestone of Spring Integration Kafka 2.0 (based on the 0.9.0.x client is now available: https://spring.io/blog/2016/04/11/spring-integration-kafka-support-2-0-0-m1-is-now-available

This is based on the new [spring-kafka](https://spring.io/blog/2016/04/11/spring-for-apache-kafka-1-0-milestone-2-available) project.

**Comment by artembilan** [comment]
Spring Integration Kafka 2.0 GA based on Spring Kafka 1.0 GA  for Kafka 0.9 has been released https://spring.io/blog/2016/07/04/spring-for-apache-kafka-1-0-and-spring-integration-kafka-2-0-go-ga.
