### ISSUE TITLE
KafkaMessageListenerContainer concurrency attribute

### ISSUE THREAD

**Issue by tonyfalabella** [spring-projects/spring-integration-kafka#95]
The `concurrency` attribute of the `KafkaMessageListenerContainer` has this for it's JavaDocs:

    /**
     * The maximum number of concurrent {@link MessageListener}s running. Messages from
     * within the same partition will be processed sequentially.
     * @param concurrency the concurrency maximum number
     */
    public void setConcurrency(int concurrency) {
    	this.concurrency = concurrency;
    }
Let's say I create a `KafkaMessageListenerContainer` that reads from individual `Partitions` of a topic and the topic has 2 partitions.  If I have `concurrency=4` I assume 4 threads will be reading those partitions.  If I need to insure that the order is preserved on a given partition (which Kafka itself guarantees) how will the threads in the listenerContainer behave?  Assume each partition has several thousand msgs and I set the listener to grab no more than 100 in a chunk.  If thread 1 grabs 100 msgs from part1, thread 2 grabs 100 msgs from part2 what will happen with thread 3 and thread 4?  Will they wait to grab msgs from part1 and part2 until the first 2 threads complete or can they potentially also grab msgs from both those parts and start processing them at the same time as the first 2 threads - in other words essentially becoming "Competing Consumers".  I assume the later.  If that is indeed the case is there any setting that will allow me to make them block until the other threads have completed with their processing before proceeding?

**Comment by garyrussell** [comment]
No; you can't have more consumers than partitions...

	Assert.isTrue(consumers <= partitions.size(),
			"The number of consumers must be smaller or equal to the number of partitions");

(`consumers == concurrency`).

**Comment by mbogoevici** [comment]
To add to what @garyrussell said - fetching and processing are separate, and there is a strong guarantee that all messages from a partition will be handled by the `messageListener` on the same thread, preserving partition ordering.

**Comment by tonyfalabella** [comment]
Thanks @mbogoevici and @garyrussell.  Based on your replies let me restate my example and understanding.
Let's say I create a `KafkaMessageListenerContainer` that reads from individual `Partitions` of a topic and the topic has 2 partitions. 
I have concurrency=2 (it cannot be greater than the number of partitions) so 2 threads will be reading those partitions. 
Assume partition 1 has 100 msgs and partition 2 has 250 msgs and I set the listener to grab no more than 100 in a chunk. 
Thread 1 grabs 100 msgs from part1, thread 2 grabs 100 msgs from part2.
Thread 1 completes processing it's 100 msgs, thread 2 is still processing it's 1st chunk of 100 msgs.
What will happen with thread 1 now?  Will it wait for msgs to arrive on partition 1 before it again does work or will it grab a chunk of 100 from partition 2 (in which case it would be a "Competing Consumer" with thread 2 on the same partition)?

Perhaps my question is a more general question, and maybe this is what @mbogoevici was mentioning.  Once a thread has grabbed messages from a partition is it then forever tied only to that partition (or at the very least not allowed to pick up any messages from any partition that currently has threads actively alive for that partition)?

**Comment by garyrussell** [comment]
Correct - partitions are tied (allocated) to threads during startup; each partition is bound to a single thread.

If you have 3 partitions and 2 threads; one of the threads will handle 1 partition, the other will handle 2.

Hence, unless the number of partitions is large, it's generally better to have the number of partitions equal to a multiple of the number of threads (assuming even work across partitions).

**Comment by tonyfalabella** [comment]
That clarifies things nicely for me @garyrussell .  Exactly what I was hoping the threads did.  Thanks.
