### ISSUE TITLE
Incorrect broker's address extraction

### ISSUE THREAD

**Issue by rssdev10** [spring-projects/spring-integration-kafka#96]
Hello, 
  I'm trying to link an application with spring integration/kafka to Flink. When I connected int-kafka:message-driven-channel-adapter (https://github.com/rssdev10/flink-spring-integration/blob/master/drpc-client/src/main/resources/flink-integration-context.xml
) the application failed with an exception 
```
Exception in thread "main" org.springframework.context.ApplicationContextException: Failed to start bean 'adapter'; nested exception is java.lang.NullPointerException at
org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:176) at
org.springframework.context.support.DefaultLifecycleProcessor.access$200(DefaultLifecycleProcessor.java:51)
...
       at kafka.client.ClientUtils$.parseBrokerList(ClientUtils.scala:102)
        at org.springframework.integration.kafka.core.DefaultConnectionFactory.refreshMetadata(DefaultConnectionFactory.java:172)
        at org.springframework.integration.kafka.core.DefaultConnectionFactory.getPartitions(DefaultConnectionFactory.java:227)

```

I began debugging and found a reason of the fail. ClientUtils$.MODULE$.parseBrokerList(brokerAddressesAsString) at the mentioned above line 172 returns null because brokerAddressesAsString contains "localhost,:9092" with comma.

And the reason is the only Broker from the following fragment contains a host with comma like this "localhost,".
```
	protected List<BrokerAddress> doGetBrokerAddresses() {
		ZkClient zkClient = null;
		try {
			zkClient = new ZkClient(this.zookeeperServers, this.sessionTimeout, this.connectionTimeout,
					ZKStringSerializer$.MODULE$);
			Seq<Broker> allBrokersInCluster = ZkUtils$.MODULE$.getAllBrokersInCluster(zkClient);
			FastList<Broker> brokers = FastList.newList(JavaConversions.asJavaCollection(allBrokersInCluster));
			return brokers.collect(brokerToBrokerAddressFunction);
		}
``` 
How to fix it?

BTW: the main purpose of this experiment is to organize gateway over kafka's messages to implement something like RPC with Flink. Unfortunately I not found ready example. May be my assumption about the gateway is incorrect. And obvious non implemented part is creation of Spring's message id by Kafka's message key. 

Client side part of the project: https://github.com/rssdev10/flink-spring-integration/tree/master/drpc-client

Thanks

**Comment by garyrussell** [comment]
There is no manipulation of the String value for the broker list; it is passed into Kafka as a property unchanged [here](https://github.com/spring-projects/spring-integration-kafka/blob/master/src/main/java/org/springframework/integration/kafka/support/ProducerFactoryBean.java#L65). Perhaps you have some other version of your config with the comma on your classpath?

**Comment by rssdev10** [comment]
Thanks, and sorry, I'm not familiar with Spring Integration.  I tried to use your examples and description from https://github.com/spring-projects/spring-integration-kafka. Like this
```
<int-kafka:message-driven-channel-adapter
            id="adapter"
            channel="output"
            connection-factory="connectionFactory"
            key-decoder="decoder"
            payload-decoder="decoder"
            offset-manager="offsetManager"
            max-fetch="100"
            topics="${kafka.test.topic}"/>
```

How to configure the broker list directly? https://github.com/rssdev10/flink-spring-integration/blob/master/drpc-client/src/main/resources/flink-integration-context.xml

BTW: what is the topics string format?

And regarding Kafka I nothing changed in they typical config.

**Comment by artembilan** [comment]
Try to use `BrokerAddressListConfiguration` instead of `ZookeeperConfiguration`.
Also it is really isn't clear why your current solution fail with the strange resolution to the `localhost,:9092`.
The code to consider ( `ZookeeperConfiguration`):
```
	zkClient = new ZkClient(this.zookeeperServers, this.sessionTimeout, this.connectionTimeout,
					ZKStringSerializer$.MODULE$);
			Seq<Broker> allBrokersInCluster = ZkUtils$.MODULE$.getAllBrokersInCluster(zkClient);
			FastList<Broker> brokers = FastList.newList(JavaConversions.asJavaCollection(allBrokersInCluster));
			return brokers.collect(brokerToBrokerAddressFunction);
```
and `DefaultConnectionFactory`:
```
String brokerAddressesAsString = ListIterate
					.collect(this.configuration.getBrokerAddresses(), Functions.getToString()).makeString(",");
```

**Comment by rssdev10** [comment]
@artembilan thanks, BrokerAddressConfiguration works. 
```
    <bean id="connectionFactory"
        class="org.springframework.integration.kafka.core.DefaultConnectionFactory">
        <!-- <constructor-arg ref="zookeeperConfiguration" />  -->
        <constructor-arg ref="brokerConfig" />
    </bean>

    <bean id="brokerConfig"
        class="org.springframework.integration.kafka.core.BrokerAddressListConfiguration">
        <constructor-arg value="#{T(org.springframework.integration.kafka.core.BrokerAddress).fromAddress('localhost:9092')}" />
    </bean>
```
But is it possible to configure one without such terrible SpEL?

**Comment by artembilan** [comment]
Just make `BrokerAddress` as inner bean!
````java
 <bean id="brokerConfig"
        class="org.springframework.integration.kafka.core.BrokerAddressListConfiguration">
        <constructor-arg>
             <bean class="org.springframework.integration.kafka.core.BrokerAddress" factory-method="fromAddress">
               <constructor-arg value="localhost:9092"/>
            </bean>
        </constructor-arg>
    </bean>
````
But SpEL should be shorter.
From other side it would be great to understand who breaks `localhost:9092` to the `localhost,:9092` for you in case of `ZookeeperConfiguration`...

Would you mind to debug your application with break points on the Spring Integration Kafka code, e.g. `ZookeeperConfiguration.doGetBrokerAddresses()` will be a good candidate?

**Comment by rssdev10** [comment]
![dogetbrokeraddresses](https://cloud.githubusercontent.com/assets/2664877/11983865/f53630f0-a9c7-11e5-852b-6b37eab57c75.png)

**Comment by artembilan** [comment]
M-m-m. Any comments, please. I'm not familiar with Eclipse:
The screenshot from IDEA:
![kafkabrokers](https://cloud.githubusercontent.com/assets/1071590/11984104/93f740ae-a986-11e5-96f4-b44d5a1cb0b5.jpg)

**Comment by artembilan** [comment]
According to your screen it really shows that Zookeeper returns `localhost,` as a host for your broker.
Not sure where that is broken, but right now it is out of our hands.
We can't control it on Spring Integration Kafka side.

**Comment by rssdev10** [comment]
Eclipse is not so hard :) . Left upper part contains a current state of variables and "localhost," is shown.

I guess the problem is somewhere in ZkUtils / getBrokerInfo(zkClient, _). 
```
  def getAllBrokersInCluster(zkClient: ZkClient): Seq[Broker] = {
    val brokerIds = ZkUtils.getChildrenParentMayNotExist(zkClient, ZkUtils.BrokerIdsPath).sorted
    brokerIds.map(_.toInt).map(getBrokerInfo(zkClient, _)).filter(_.isDefined).map(_.get)
  }
```
Kafka for me is new product too. I can't comment anything.

**Comment by rssdev10** [comment]
I found the reason. /etc/hosts contained a comma as a separator....
```
127.0.0.1       localhost, linux-...
```
When I fixed it and restarted Kafka the application was started correctly.
Thanks for the advises. And please add error info in doGetBrokerAddresses() to avoid anonymous java.lang.NullPointerException.

**Comment by artembilan** [comment]
Thank you for the final solution!

Yes, we definitely should fix it.
Doing that now...

**Comment by artembilan** [comment]
Well, I'm not sure that we can do here so much:
```
java.lang.NullPointerException
	at scala.Predef$.Integer2int(Predef.scala:392)
	at kafka.client.ClientUtils$$anonfun$parseBrokerList$1.apply(ClientUtils.scala:103)
	at kafka.client.ClientUtils$$anonfun$parseBrokerList$1.apply(ClientUtils.scala:102)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:47)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
	at scala.collection.AbstractTraversable.map(Traversable.scala:105)
	at kafka.client.ClientUtils$.parseBrokerList(ClientUtils.scala:102)
	at org.springframework.integration.kafka.core.DefaultConnectionFactory.refreshMetadata(DefaultConnectionFactory.java:175)
```
Looks like Kafka should take care about the `null` for the port.

Anyway, I'll throw some `IllegalState` for the `ClientUtils$.parseBrokerList` with the appropriate `brokerAddressesAsString` to see the issue in the logs.

**Comment by artembilan** [comment]
See #98
